2022-12-10 10:21:48 info: ---------------------------------------
2022-12-10 10:21:48 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-12-10 10:21:48 info: ---------------------------------------
2022-12-10 10:21:53 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    √ should exist and be executable (2 ms)
    × should have all TODO comments removed (2 ms)
    √ `getAnonName` should not contain unneeded console.log calls
    √ should call `new Promise()`
    √ should take a single argument (1 ms)
    √ `resolve()` should be called with a one argument (1 ms)
    √ `reject()` should be called with a one argument
    √ should resolve when called with a string argument (3 ms)
    √ should reject with an Error object when called without an argument (1 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        1.159 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-12-10 10:22:39 info: ---------------------------------------
2022-12-10 10:22:39 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-12-10 10:22:39 info: ---------------------------------------
2022-12-10 10:22:42 info: All unit tests passed.
2022-12-10 10:22:49 info: All steps were completed successfully
2022-12-10 10:34:19 info: -------------------------------------------------
2022-12-10 10:34:19 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-12-10 10:34:19 info: -------------------------------------------------
2022-12-10 10:34:23 error: *** Unit Test Error Report ***

Command failed: npx jest ex2-checkDoubleDigits.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js
  checkDoubleDigits
    √ should exist and be executable (2 ms)
    √ should have all TODO comments removed (1 ms)
    √ `checkDoubleDigits` should not contain unneeded console.log calls (1 ms)
    √ should call new Promise()
    √ `resolve()` should be called with a one argument (1 ms)
    √ `reject()` should be called with a one argument
    √ should be a function that takes a single argument
    × (9) should return a rejected promise with an Error object (2 ms)
    × (10) should return a promise that resolves to "This is a double digit number!" (1 ms)
    × (99) should return a promise that resolves to "This is a double digit number!" (1 ms)
    × (100) should return a rejected promise with an Error object (1 ms)

  ● checkDoubleDigits › (9) should return a rejected promise with an Error object

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "Expected a double digit number but got 9"

      65 |     const promise = checkDoubleDigits(9);
      66 |     expect(promise).toBeInstanceOf(Promise);
    > 67 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      68 |   });
      69 |
      70 |   test('(10) should return a promise that resolves to "This is a double digit number!"', () => {

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:210:22)
      at Object.toBeInstanceOf (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:67:36)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: "Expected a double digit number but got 10"

      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);
    > 75 |     return expect(promise).resolves.toEqual(
         |            ^
      76 |       expect.stringContaining('This is a double digit number!')
      77 |     );
      78 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:75:12)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      69 |
      70 |   test('(10) should return a promise that resolves to "This is a double digit number!"', () => {
    > 71 |     expect.assertions(3);
         |            ^
      72 |     expect(exported).toBeDefined();
      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:71:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: "Expected a double digit number but got 99"

      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
    > 84 |     return expect(promise).resolves.toEqual(
         |            ^
      85 |       expect.stringContaining('This is a double digit number!')
      86 |     );
      87 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:84:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      79 |
      80 |   test('(99) should return a promise that resolves to "This is a double digit number!"', () => {
    > 81 |     expect.assertions(2);
         |            ^
      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
      84 |     return expect(promise).resolves.toEqual(

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:81:12)

  ● checkDoubleDigits › (100) should return a rejected promise with an Error object

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "Expected a double digit number but got 100"

      91 |     const promise = checkDoubleDigits(100);
      92 |     expect(promise).toBeInstanceOf(Promise);
    > 93 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      94 |   });
      95 | });
      96 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:210:22)
      at Object.toBeInstanceOf (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:93:36)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 7 passed, 11 total
Snapshots:   0 total
Time:        0.992 s
Ran all test suites matching /ex2-checkDoubleDigits.test.js/i.
2022-12-10 10:36:03 info: -------------------------------------------------
2022-12-10 10:36:03 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-12-10 10:36:03 info: -------------------------------------------------
2022-12-10 10:36:07 error: *** Unit Test Error Report ***

Command failed: npx jest ex2-checkDoubleDigits.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js
  checkDoubleDigits
    √ should exist and be executable (3 ms)
    √ should have all TODO comments removed (2 ms)
    √ `checkDoubleDigits` should not contain unneeded console.log calls (2 ms)
    √ should call new Promise() (1 ms)
    √ `resolve()` should be called with a one argument (6 ms)
    √ `reject()` should be called with a one argument (1 ms)
    √ should be a function that takes a single argument (1 ms)
    × (9) should return a rejected promise with an Error object (5 ms)
    × (10) should return a promise that resolves to "This is a double digit number!" (8 ms)
    × (99) should return a promise that resolves to "This is a double digit number!" (1 ms)
    × (100) should return a rejected promise with an Error object (1 ms)

  ● checkDoubleDigits › (9) should return a rejected promise with an Error object

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "Expected a double digit number but got 9"

      65 |     const promise = checkDoubleDigits(9);
      66 |     expect(promise).toBeInstanceOf(Promise);
    > 67 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      68 |   });
      69 |
      70 |   test('(10) should return a promise that resolves to "This is a double digit number!"', () => {

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:210:22)
      at Object.toBeInstanceOf (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:67:36)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: "Expected a double digit number but got 10"

      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);
    > 75 |     return expect(promise).resolves.toEqual(
         |            ^
      76 |       expect.stringContaining('This is a double digit number!')
      77 |     );
      78 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:75:12)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      69 |
      70 |   test('(10) should return a promise that resolves to "This is a double digit number!"', () => {
    > 71 |     expect.assertions(3);
         |            ^
      72 |     expect(exported).toBeDefined();
      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:71:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: "Expected a double digit number but got 99"

      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
    > 84 |     return expect(promise).resolves.toEqual(
         |            ^
      85 |       expect.stringContaining('This is a double digit number!')
      86 |     );
      87 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:84:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      79 |
      80 |   test('(99) should return a promise that resolves to "This is a double digit number!"', () => {
    > 81 |     expect.assertions(2);
         |            ^
      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
      84 |     return expect(promise).resolves.toEqual(

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:81:12)

  ● checkDoubleDigits › (100) should return a rejected promise with an Error object

    expect(received).rejects.toBeInstanceOf(expected)

    Expected constructor: Error

    Received value has no prototype
    Received value: "Expected a double digit number but got 100"

      91 |     const promise = checkDoubleDigits(100);
      92 |     expect(promise).toBeInstanceOf(Promise);
    > 93 |     return expect(promise).rejects.toBeInstanceOf(Error);
         |                                    ^
      94 |   });
      95 | });
      96 |

      at Object.toBeInstanceOf (node_modules/expect/build/index.js:210:22)
      at Object.toBeInstanceOf (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:93:36)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 7 passed, 11 total
Snapshots:   0 total
Time:        0.999 s, estimated 1 s
Ran all test suites matching /ex2-checkDoubleDigits.test.js/i.
2022-12-10 10:39:54 info: -------------------------------------------------
2022-12-10 10:39:54 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-12-10 10:39:54 info: -------------------------------------------------
2022-12-10 10:39:58 error: *** Unit Test Error Report ***

Command failed: npx jest ex2-checkDoubleDigits.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js
  checkDoubleDigits
    √ should exist and be executable (2 ms)
    √ should have all TODO comments removed (2 ms)
    √ `checkDoubleDigits` should not contain unneeded console.log calls (2 ms)
    √ should call new Promise() (1 ms)
    √ `resolve()` should be called with a one argument (1 ms)
    √ `reject()` should be called with a one argument
    √ should be a function that takes a single argument (1 ms)
    √ (9) should return a rejected promise with an Error object (3 ms)
    × (10) should return a promise that resolves to "This is a double digit number!" (5 ms)
    × (99) should return a promise that resolves to "This is a double digit number!" (2 ms)
    √ (100) should return a rejected promise with an Error object (1 ms)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: [Error: Expected a double digit number but got 10]

      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);
    > 75 |     return expect(promise).resolves.toEqual(
         |            ^
      76 |       expect.stringContaining('This is a double digit number!')
      77 |     );
      78 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:75:12)

  ● checkDoubleDigits › (10) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      69 |
      70 |   test('(10) should return a promise that resolves to "This is a double digit number!"', () => {
    > 71 |     expect.assertions(3);
         |            ^
      72 |     expect(exported).toBeDefined();
      73 |     const promise = checkDoubleDigits(10);
      74 |     expect(promise).toBeInstanceOf(Promise);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:71:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect(received).resolves.toEqual()

    Received promise rejected instead of resolved
    Rejected to value: [Error: Expected a double digit number but got 99]

      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
    > 84 |     return expect(promise).resolves.toEqual(
         |            ^
      85 |       expect.stringContaining('This is a double digit number!')
      86 |     );
      87 |   });

      at expect (node_modules/expect/build/index.js:105:15)
      at Object.expect (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:84:12)

  ● checkDoubleDigits › (99) should return a promise that resolves to "This is a double digit number!"

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      79 |
      80 |   test('(99) should return a promise that resolves to "This is a double digit number!"', () => {
    > 81 |     expect.assertions(2);
         |            ^
      82 |     const promise = checkDoubleDigits(99);
      83 |     expect(promise).toBeInstanceOf(Promise);
      84 |     return expect(promise).resolves.toEqual(

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex2-checkDoubleDigits.test.js:81:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 9 passed, 11 total
Snapshots:   0 total
Time:        0.982 s, estimated 1 s
Ran all test suites matching /ex2-checkDoubleDigits.test.js/i.
2022-12-10 10:41:13 info: -------------------------------------------------
2022-12-10 10:41:13 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-12-10 10:41:13 info: -------------------------------------------------
2022-12-10 10:41:17 info: All unit tests passed.
2022-12-10 10:41:24 info: All steps were completed successfully
2022-12-10 11:20:08 info: ---------------------------------------
2022-12-10 11:20:08 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:20:08 info: ---------------------------------------
2022-12-10 11:20:12 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    √ should exist and be executable (2 ms)
    × should have all TODO comments removed (2 ms)
    × should call `new Promise()`
    × `resolve()` should be called with a one argument (2 ms)
    × `reject()` should be called with a one argument (1 ms)
    × should resolve when the die settles successfully (1 ms)
    × should reject with an Error when the die rolls off the table (1 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● rollDie › should call `new Promise()`

    expect(received).toBeDefined()

    Received: undefined

      38 |
      39 |   test('should call `new Promise()`', () => {
    > 40 |     expect(state.newPromise).toBeDefined();
         |                              ^
      41 |   });
      42 |
      43 |   test('`resolve()` should be called with a one argument', () => {

      at Object.toBeDefined (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:40:30)

  ● rollDie › `resolve()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      42 |
      43 |   test('`resolve()` should be called with a one argument', () => {
    > 44 |     expect(state.resolve).toBe(1);
         |                           ^
      45 |   });
      46 |
      47 |   test('`reject()` should be called with a one argument', () => {

      at Object.toBe (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:44:27)

  ● rollDie › `reject()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      46 |
      47 |   test('`reject()` should be called with a one argument', () => {
    > 48 |     expect(state.reject).toBe(1);
         |                          ^
      49 |   });
      50 |
      51 |   test('should resolve when the die settles successfully', () => {

      at Object.toBe (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:48:26)

  ● rollDie › should resolve when the die settles successfully

    TypeError: callback is not a function

      32 |     if (roll === randomRollsToDo) {
      33 |       // TODO replace "success" callback
    > 34 |       callback(null, value);
         |       ^
      35 |     }
      36 |
      37 |     // Schedule the next roll todo until no more rolls to do

      at callback (3-UsingAPIs/Week1/homework/ex3-rollDie.js:34:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:39:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:39:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:39:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:39:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:44:3)
      at Object.rollDie (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:61:21)

  ● rollDie › should resolve when the die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received one assertion call.

      50 |
      51 |   test('should resolve when the die settles successfully', () => {
    > 52 |     expect.assertions(3);
         |            ^
      53 |     expect(exported).toBeDefined();
      54 |
      55 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:52:12)

  ● rollDie › should reject with an Error when the die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      73 |
      74 |   test('should reject with an Error when the die rolls off the table', async () => {
    > 75 |     expect.assertions(3);
         |            ^
      76 |     expect(exported).toBeDefined();
      77 |
      78 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:75:12)

Test Suites: 1 failed, 1 total
Tests:       6 failed, 1 passed, 7 total
Snapshots:   0 total
Time:        0.949 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-12-10 11:29:07 info: ---------------------------------------
2022-12-10 11:29:07 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:29:07 info: ---------------------------------------
2022-12-10 11:29:11 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    √ should exist and be executable (3 ms)
    × should have all TODO comments removed (4 ms)
    × should call `new Promise()` (1 ms)
    × `resolve()` should be called with a one argument (4 ms)
    √ `reject()` should be called with a one argument (1 ms)
    × should resolve when the die settles successfully (3 ms)
    × should reject with an Error when the die rolls off the table (4 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● rollDie › should call `new Promise()`

    expect(received).toBeDefined()

    Received: undefined

      38 |
      39 |   test('should call `new Promise()`', () => {
    > 40 |     expect(state.newPromise).toBeDefined();
         |                              ^
      41 |   });
      42 |
      43 |   test('`resolve()` should be called with a one argument', () => {

      at Object.toBeDefined (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:40:30)

  ● rollDie › `resolve()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      42 |
      43 |   test('`resolve()` should be called with a one argument', () => {
    > 44 |     expect(state.resolve).toBe(1);
         |                           ^
      45 |   });
      46 |
      47 |   test('`reject()` should be called with a one argument', () => {

      at Object.toBe (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:44:27)

  ● rollDie › should resolve when the die settles successfully

    TypeError: resolve is not a function

      30 |     // Use callback to communicate the final die value once finished rolling
      31 |     if (roll === randomRollsToDo) {
    > 32 |       resolve(null, value);
         |       ^
      33 |     }
      34 |
      35 |     // Schedule the next roll todo until no more rolls to do

      at resolve (3-UsingAPIs/Week1/homework/ex3-rollDie.js:32:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:42:3)
      at Object.rollDie (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:61:21)

  ● rollDie › should resolve when the die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received one assertion call.

      50 |
      51 |   test('should resolve when the die settles successfully', () => {
    > 52 |     expect.assertions(3);
         |            ^
      53 |     expect(exported).toBeDefined();
      54 |
      55 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:52:12)

  ● rollDie › should reject with an Error when the die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      73 |
      74 |   test('should reject with an Error when the die rolls off the table', async () => {
    > 75 |     expect.assertions(3);
         |            ^
      76 |     expect(exported).toBeDefined();
      77 |
      78 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:75:12)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 2 passed, 7 total
Snapshots:   0 total
Time:        1.128 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-12-10 11:31:04 info: ---------------------------------------
2022-12-10 11:31:04 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:31:04 info: ---------------------------------------
2022-12-10 11:31:08 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    √ should exist and be executable (2 ms)
    × should have all TODO comments removed (2 ms)
    × should call `new Promise()` (1 ms)
    √ `resolve()` should be called with a one argument (1 ms)
    √ `reject()` should be called with a one argument (1 ms)
    × should resolve when the die settles successfully (2 ms)
    × should reject with an Error when the die rolls off the table (3 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● rollDie › should call `new Promise()`

    expect(received).toBeDefined()

    Received: undefined

      38 |
      39 |   test('should call `new Promise()`', () => {
    > 40 |     expect(state.newPromise).toBeDefined();
         |                              ^
      41 |   });
      42 |
      43 |   test('`resolve()` should be called with a one argument', () => {

      at Object.toBeDefined (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:40:30)

  ● rollDie › should resolve when the die settles successfully

    TypeError: resolve is not a function

      30 |     // Use callback to communicate the final die value once finished rolling
      31 |     if (roll === randomRollsToDo) {
    > 32 |       resolve(value);
         |       ^
      33 |     }
      34 |
      35 |     // Schedule the next roll todo until no more rolls to do

      at resolve (3-UsingAPIs/Week1/homework/ex3-rollDie.js:32:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:24)
      at cb (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:59:35)
      at setTimeout (3-UsingAPIs/Week1/homework/ex3-rollDie.js:37:7)
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDie.js:42:3)
      at Object.rollDie (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:61:21)

  ● rollDie › should resolve when the die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received one assertion call.

      50 |
      51 |   test('should resolve when the die settles successfully', () => {
    > 52 |     expect.assertions(3);
         |            ^
      53 |     expect(exported).toBeDefined();
      54 |
      55 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:52:12)

  ● rollDie › should reject with an Error when the die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      73 |
      74 |   test('should reject with an Error when the die rolls off the table', async () => {
    > 75 |     expect.assertions(3);
         |            ^
      76 |     expect(exported).toBeDefined();
      77 |
      78 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js:75:12)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 3 passed, 7 total
Snapshots:   0 total
Time:        0.975 s, estimated 2 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-12-10 11:43:28 info: ---------------------------------------
2022-12-10 11:43:28 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:43:28 info: ---------------------------------------
2022-12-10 11:43:32 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDie.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDie.test.js
  rollDie
    √ should exist and be executable (4 ms)
    × should have all TODO comments removed (4 ms)
    √ should call `new Promise()`
    √ `resolve()` should be called with a one argument (1 ms)
    √ `reject()` should be called with a one argument (1 ms)
    √ should resolve when the die settles successfully (3 ms)
    √ should reject with an Error when the die rolls off the table (2 ms)

  ● rollDie › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.061 s
Ran all test suites matching /ex3-rollDie.test.js/i.
2022-12-10 11:44:56 info: ---------------------------------------
2022-12-10 11:44:56 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:44:56 info: ---------------------------------------
2022-12-10 11:44:59 info: All unit tests passed.
2022-12-10 11:45:06 info: All steps were completed successfully
2022-12-10 11:49:40 info: ---------------------------------------
2022-12-10 11:49:40 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-12-10 11:49:40 info: ---------------------------------------
2022-12-10 11:49:44 info: All unit tests passed.
2022-12-10 11:49:50 info: All steps were completed successfully
2022-12-11 01:19:54 info: --------------------------------------------
2022-12-11 01:19:54 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:19:54 info: --------------------------------------------
2022-12-11 01:19:59 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    √ should exist and be executable (2 ms)
    √ should have all TODO comments removed (1 ms)
    √ `rollDice` should not contain unneeded console.log calls (1 ms)
    √ should use `dice.map()` (1 ms)
    √ should use `Promise.all()`
    √ should resolve when all dice settle successfully (2 ms)
    × should reject with an Error when a die rolls off the table (1 ms)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.191 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64
        reject(new Error(`Die ${die} rolled off the table.\n`));
               ^

Error: Die 1 rolled off the table.

    at rollOnce (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64:16)
    at Timeout._onTimeout (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:77:26)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-12-11 01:20:02 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  27:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-12-11 01:24:21 info: --------------------------------------------
2022-12-11 01:24:21 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:24:21 info: --------------------------------------------
2022-12-11 01:24:25 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    √ should exist and be executable (2 ms)
    √ should have all TODO comments removed (1 ms)
    √ `rollDice` should not contain unneeded console.log calls (1 ms)
    √ should use `dice.map()` (1 ms)
    √ should use `Promise.all()`
    √ should resolve when all dice settle successfully (5 ms)
    × should reject with an Error when a die rolls off the table (3 ms)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.03 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64
        reject(new Error(`Die ${die} rolled off the table.\n`));
               ^

Error: Die 1 rolled off the table.

    at rollOnce (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64:16)
    at Timeout._onTimeout (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:77:26)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-12-11 01:27:57 info: --------------------------------------------
2022-12-11 01:27:57 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:27:57 info: --------------------------------------------
2022-12-11 01:28:01 info: All unit tests passed.
2022-12-11 01:28:08 info: All steps were completed successfully
2022-12-11 01:29:05 info: --------------------------------------------
2022-12-11 01:29:05 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:29:05 info: --------------------------------------------
2022-12-11 01:29:09 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    √ should exist and be executable (4 ms)
    √ should have all TODO comments removed (2 ms)
    √ `rollDice` should not contain unneeded console.log calls (2 ms)
    √ should use `dice.map()` (1 ms)
    √ should use `Promise.all()` (1 ms)
    √ should resolve when all dice settle successfully (5 ms)
    × should reject with an Error when a die rolls off the table (2 ms)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.02 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64
        reject(new Error(`Die ${die} rolled off the table.\n`));
               ^

Error: Die 1 rolled off the table.

    at rollOnce (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64:16)
    at Timeout._onTimeout (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:77:26)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-12-11 01:30:10 info: --------------------------------------------
2022-12-11 01:30:10 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:30:10 info: --------------------------------------------
2022-12-11 01:30:15 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    √ should exist and be executable (2 ms)
    √ should have all TODO comments removed (1 ms)
    √ `rollDice` should not contain unneeded console.log calls (1 ms)
    √ should use `dice.map()`
    √ should use `Promise.all()` (1 ms)
    √ should resolve when all dice settle successfully (2 ms)
    × should reject with an Error when a die rolls off the table (1 ms)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.assertions (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        0.847 s, estimated 1 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64
        reject(new Error(`Die ${die} rolled off the table.\n`));
               ^

Error: Die 1 rolled off the table.

    at rollOnce (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:64:16)
    at Timeout._onTimeout (C:\Users\Gebruiker\Homework-class41\3-UsingAPIs\helpers\pokerDiceRoller.js:77:26)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-12-11 01:31:24 info: --------------------------------------------
2022-12-11 01:31:24 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-12-11 01:31:24 info: --------------------------------------------
2022-12-11 01:31:28 info: All unit tests passed.
2022-12-11 01:31:34 info: All steps were completed successfully
2022-12-11 01:41:13 info: ----------------------------------------------
2022-12-11 01:41:13 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-12-11 01:41:13 info: ----------------------------------------------
2022-12-11 01:41:17 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (2 ms)
    × should have all TODO comments removed (2 ms)
    √ `rollDice` should not contain unneeded console.log calls (1 ms)
    √ should resolve when all dice settle successfully (128 ms)
    √ should reject with an Error when a die rolls off the table (94 ms)

  ● ex5-pokerDiceChain › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        1.151 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.
2022-12-11 01:42:28 info: ----------------------------------------------
2022-12-11 01:42:28 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-12-11 01:42:28 info: ----------------------------------------------
2022-12-11 01:42:32 info: All unit tests passed.
2022-12-11 01:42:39 info: All steps were completed successfully
2022-12-18 11:26:55 info: ---------------------------------------------
2022-12-18 11:26:55 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-12-18 11:26:55 info: ---------------------------------------------
2022-12-18 11:27:04 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-programmerFun.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js
  programmerFun
    √ HTML should be syntactically valid (176 ms)
    × should have all TODO comments removed (2 ms)
    × should use `fetch()`
    × should use async/wait (1 ms)
    × should use try/catch (1 ms)

  ● programmerFun › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● programmerFun › should use `fetch()`

    expect(received).toBeDefined()

    Received: undefined

      48 |
      49 |   test('should use `fetch()`', () => {
    > 50 |     expect(state.fetch).toBeDefined();
         |                         ^
      51 |   });
      52 |
      53 |   test('should use async/wait', () => {

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:50:25)

  ● programmerFun › should use async/wait

    expect(received).toBeDefined()

    Received: undefined

      52 |
      53 |   test('should use async/wait', () => {
    > 54 |     expect(state.async).toBeDefined();
         |                         ^
      55 |     expect(state.await).toBeDefined();
      56 |   });
      57 |

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:54:25)

  ● programmerFun › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      57 |
      58 |   test('should use try/catch', () => {
    > 59 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      60 |   });
      61 | });
      62 |

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:59:28)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 1 passed, 5 total
Snapshots:   0 total
Time:        4.995 s
Ran all test suites matching /ex1-programmerFun.test.js/i.
2022-12-18 11:27:07 error: *** ESLint Report ***

ex1-programmerFun/index.js
  20:22  error  'url' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-12-18 11:34:54 info: ---------------------------------------------
2022-12-18 11:34:54 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-12-18 11:34:54 info: ---------------------------------------------
2022-12-18 11:35:01 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-programmerFun.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js
  programmerFun
    √ HTML should be syntactically valid (215 ms)
    × should have all TODO comments removed (2 ms)
    √ should use `fetch()`
    √ should use async/wait
    × should use try/catch (1 ms)

  ● programmerFun › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● programmerFun › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      57 |
      58 |   test('should use try/catch', () => {
    > 59 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      60 |   });
      61 | });
      62 |

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:59:28)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        4.61 s, estimated 5 s
Ran all test suites matching /ex1-programmerFun.test.js/i.
2022-12-19 12:02:04 info: ---------------------------------------------
2022-12-19 12:02:04 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-12-19 12:02:04 info: ---------------------------------------------
2022-12-19 12:02:11 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-programmerFun.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js
  programmerFun
    √ HTML should be syntactically valid (203 ms)
    × should have all TODO comments removed (2 ms)
    √ should use `fetch()`
    √ should use async/wait
    × should use try/catch

  ● programmerFun › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.toBeFalsy (test-runner/unit-test-helpers.js:105:42)

  ● programmerFun › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      57 |
      58 |   test('should use try/catch', () => {
    > 59 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      60 |   });
      61 | });
      62 |

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:59:28)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
Snapshots:   0 total
Time:        4.097 s, estimated 5 s
Ran all test suites matching /ex1-programmerFun.test.js/i.
2022-12-19 12:02:56 info: ---------------------------------------------
2022-12-19 12:02:56 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-12-19 12:02:56 info: ---------------------------------------------
2022-12-19 12:03:03 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-programmerFun.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js
  programmerFun
    √ HTML should be syntactically valid (168 ms)
    √ should have all TODO comments removed (1 ms)
    √ should use `fetch()`
    √ should use async/wait
    × should use try/catch (2 ms)

  ● programmerFun › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      57 |
      58 |   test('should use try/catch', () => {
    > 59 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      60 |   });
      61 | });
      62 |

      at Object.toBeDefined (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:59:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        3.94 s, estimated 5 s
Ran all test suites matching /ex1-programmerFun.test.js/i.
2022-12-19 12:07:05 info: ---------------------------------------------
2022-12-19 12:07:05 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-12-19 12:07:05 info: ---------------------------------------------
2022-12-19 12:07:12 info: All unit tests passed.
2022-12-19 12:07:18 info: All steps were completed successfully
